### ISSUE TITLE
1.19.2 Crash

### ISSUE THREAD

**Issue by QianFuv** [Catscythe-Corner/Peculiars#1]
https://mclo.gs/mKyFZV8
https://mclo.gs/O0o3RU7

**Comment by QianFuv** [comment]
When the cursor is placed on a certain food, the game completely crashes.

**Comment by linkovich2** [comment]
afaict this is happening with the new atmospheric beta. I'm getting the same

**Comment by QianFuv** [comment]
This project is almost dead?
