### ISSUE TITLE
Game Crash with AppleSkin

### ISSUE THREAD

**Issue by Antirhinnum** [Catscythe-Corner/Peculiars#2]
Same issue as #1, but with more details.

If this mod and [AppleSkin](https://www.curseforge.com/minecraft/mc-mods/appleskin) are both installed, when any food item from this mod is hovered over (in the inventory, JEI/similar, etc.), the game crashes. This issue is resolved if Atmospheric (5.0.0) is installed.

Ideally, the Atmospheric-related content from this mod shouldn't load if Atmospheric isn't enabled, especially since Atmospheric isn't listed as a required dependency, nor is it required to load Peculiars.

![image](https://github.com/Catscythe-Corner/Peculiars/assets/33076411/af896cfa-83db-434f-b6d5-f45e36055d4e)

Log (without Atmospheric installed): https://mclo.gs/hE91TrN

Versions:

- _Minecraft_: 1.19.2
- Forge: 43.3.7
- AppleSkin: 2.4.2
- Blueprint: 6.2.0
- Neapolitan: 4.1.0
- Peculiars: 4.1.0

**Comment by WordStormRose** [comment]
I'm encountering basically the same crash in 1.18.2, though specifically the yucca ice cream appears to be the trigger for the crash.

**Comment by Uraneptus** [comment]
Hi, sorry for the late response. For some reason I won't get notified when there are issues opened here :/
I will however look into this crash soon!

**Comment by Uraneptus** [comment]
> Same issue as #1, but with more details.
> 
> If this mod and [AppleSkin](https://www.curseforge.com/minecraft/mc-mods/appleskin) are both installed, when any food item from this mod is hovered over (in the inventory, JEI/similar, etc.), the game crashes. This issue is resolved if Atmospheric (5.0.0) is installed.
> 
> Ideally, the Atmospheric-related content from this mod shouldn't load if Atmospheric isn't enabled, especially since Atmospheric isn't listed as a required dependency, nor is it required to load Peculiars.
> 
> ![image](https://private-user-images.githubusercontent.com/33076411/296607716-af896cfa-83db-434f-b6d5-f45e36055d4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzMzIxNTYsIm5iZiI6MTcwOTMzMTg1NiwicGF0aCI6Ii8zMzA3NjQxMS8yOTY2MDc3MTYtYWY4OTZjZmEtODNkYi00MzRmLWI2ZDUtZjQ1ZTM2MDU1ZDRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDIyMjQxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmZDJmMTgyNjdkN2FkNzdiZmYxNGU3ZmRlZTBhYmY4N2UwOWExOTdmZjM5NmMzZTVjN2NlM2VhM2NkNzExZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iuECkJ7thT_4br0JymwJKOH3iRowBJW-UCjbMpr7zjg)
> 
> Log (without Atmospheric installed): https://mclo.gs/hE91TrN
> 
> Versions:
> 
> * _Minecraft_: 1.19.2
> * Forge: 43.3.7
> * AppleSkin: 2.4.2
> * Blueprint: 6.2.0
> * Neapolitan: 4.1.0
> * Peculiars: 4.1.0

I think the best fix for this would be hiding the items from the creative inventory, because you can't otherwise aquire them and optional registration is not very safe. However I must ask, why are you using this mod without Atmospheric installed?? Without Atmospheric this mod doesn't do anything atm.

**Comment by Antirhinnum** [comment]
> However I must ask, why are you using this mod without Atmospheric installed?? Without Atmospheric this mod doesn't do anything atm.

A friend included Peculiars in a modpack -- I have no idea why they didn't include Atmospheric. My best guess is they were just looking for Neapolitan addons and didn't read and see this mod only added obtainable content if Atmospheric was enabled.

Either way, thank you for the response and fix!
