### ISSUE TITLE
Crash when eating any food with Atmospheric beta

### ISSUE THREAD

**Issue by valchiara** [Catscythe-Corner/Peculiars#3]
When eating any food, the game crashes.

Minecraft 1.19.2
Peculiars 1.19.2-4.1.0
Atmospheric 5.1.0-beta1

https://pastebin.com/LNHAGyHf

**Comment by Uraneptus** [comment]
Since you opened this 5 days ago, I suppose the Atmospheric file was from the supporter channel on their discord?
