### ISSUE TITLE
Crash while eating Passionfruit Tart

### ISSUE THREAD

**Issue by AdikaraAdnan** [Catscythe-Corner/Peculiars#4]
I was testing my modpack, which was crashing at first due to the Guard Villager mod but relating to the passionfruit tart, after I updated the other mod, their problem seems to be gone but the game crashes after I tried eating the passionfruit tart myself :
https://mclo.gs/8VNw4l8

**Comment by Uraneptus** [comment]
I'll fix that as soon as possible!
